// 名人名言：英 + 中，页面切换时随机展示
globalThis.WINDOW_QUOTES = [
  ["The only way to do great work is to love what you do.", "做出伟大工作的唯一途径是热爱你所做的事。—— 乔布斯"],
  ["Success is not final, failure is not fatal: it is the courage to continue that counts.", "成功不是终点，失败也并非致命，重要的是继续前行的勇气。—— 丘吉尔"],
  ["Life is what happens when you're busy making other plans.", "生活就是当你忙于制定其他计划时发生的事。—— 列侬"],
  ["The future belongs to those who believe in the beauty of their dreams.", "未来属于那些相信自己梦想之美的人。—— 罗斯福"],
  ["It always seems impossible until it's done.", "事情在做成之前，总显得不可能。—— 曼德拉"],
  ["Whether you think you can or you think you can't, you're right.", "你认为自己能行或不行，你都是对的。—— 福特"],
  ["The best time to plant a tree was 20 years ago. The second best time is now.", "种树最好的时间是二十年前，其次是现在。—— 中国谚语"],
  ["In the middle of difficulty lies opportunity.", "困难之中蕴藏着机会。—— 爱因斯坦"],
  ["Do what you can, with what you have, where you are.", "用你拥有的，在你所在的地方，做你能做的事。—— 罗斯福"],
  ["The journey of a thousand miles begins with one step.", "千里之行，始于足下。—— 老子"],
  ["Genius is one percent inspiration and ninety-nine percent perspiration.", "天才是百分之一的灵感加百分之九十九的汗水。—— 爱迪生"],
  ["Well done is better than well said.", "做得漂亮胜过说得漂亮。—— 富兰克林"],
  ["He who has a why to live can bear almost any how.", "知道自己为何而活的人，能承受几乎任何苦难。—— 尼采"],
  ["Simplicity is the ultimate sophistication.", "简单是终极的精致。—— 达·芬奇"],
  ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "我们反复做什么，就会成为什么。卓越不是一种行为，而是一种习惯。—— 亚里士多德"],
  ["The only thing we have to fear is fear itself.", "我们唯一需要恐惧的，就是恐惧本身。—— 罗斯福"],
  ["Fall seven times, stand up eight.", "跌倒七次，就站起来八次。—— 日本谚语"],
  ["A person who never made a mistake never tried anything new.", "从不犯错的人，也从没有尝试过新事物。—— 爱因斯坦"],
  ["Nothing is impossible, the word itself says 'I'm possible'!", "没有什么不可能，不可能这个词本身就写着“我是可能的”。—— 奥黛丽·赫本"],
  ["The secret of getting ahead is getting started.", "领先的秘诀就是开始行动。—— 马克·吐温"],
  ["Don't watch the clock; do what it does. Keep going.", "不要盯着时钟，要像时钟一样一直走下去。—— 萨姆·莱文森"],
  ["What we achieve inwardly will change outer reality.", "我们在内心取得的成就，会改变外在的现实。—— 普鲁塔克"],
  ["Turn your wounds into wisdom.", "把伤痕变成智慧。—— 奥普拉·温弗瑞"],
  ["Knowledge is power.", "知识就是力量。—— 培根"],
  ["Aim for the moon. If you miss, you may hit a star.", "瞄准月亮，即使错过，你也可能击中一颗星星。—— 克莱门特·斯通"],
  ["Reading is to the mind what exercise is to the body.", "阅读之于心灵，正如运动之于身体。—— 艾迪生"],
  ["Dream big and dare to fail.", "心怀大梦，敢于失败。—— 诺曼·沃恩"],
  ["The best way to predict the future is to invent it.", "预测未来的最好方式就是创造未来。—— 凯伊"],
  ["Action is the foundational key to all success.", "行动是一切成功的基础。—— 毕加索"],
  ["Perseverance is not a long race; it is many short races one after another.", "坚持不是一场长跑，而是一场接一场的短跑。—— 沃尔特·艾略特"],
];
